name: panrd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.8.6
  - python_abi=3.8
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.34.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - -r file:requirements.txt
variables:
  CUDAHOME: /usr/local/cuda-10.2/