channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - cuda=11.8.0
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-demo-suite=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - gcc=11.2.0
  - gcc_impl_linux-64=11.2.0
  - gds-tools=1.4.0.31
  - gxx=11.2.0
  - gxx_impl_linux-64=11.2.0
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.36.1
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libffi=3.4.2
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libsanitizer=11.2.0
  - libsqlite=3.40.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - nsight-compute=2022.3.0.22
  - openssl=3.0.8
  - pip=23.0.1
  - python=3.10.9
  - readline=8.1.2
  - setuptools=67.6.0
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
