[project]
authors = ["Carlos Loucera <carlos.loucera@juntadeandalucia.es>"]
channels = ["conda-forge", "bioconda", "anaconda"]
description = "Add a short description here"
name = "hipathia"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
linux = "4"

[feature.r.dependencies]
bioconductor-hipathia = ">=3.2.0,<4"
r-here = ">=1.0.1,<2"
"r-data.table" = ">=1.15.4,<2"
r-feather = ">=0.3.5,<0.4"
bioconductor-edger = ">=4.0.16,<5"
bioconductor-biocversion = "3.18.*"
r-base = "4.3.*"
"r-r.utils" = ">=2.12.3,<3"
bioconductor-genomeinfodbdata = ">=1.2.11,<2"

[feature.r.activation]
scripts = ["env_setup.sh"]

[feature.py.dependencies]
python = "3.10.*"
# click = "*"
# pandas = "*"
# biothings_client = "*"
#pyarrow = "*"

[feature.py.pypi-dependencies]
drexml = "*"
biothings_client = "*"
pandas = "*"
click = "*"

[environments]
# all environments include the default feature
py = ["py"]
r = ["r"]
